apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helmscratch-be-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helmscratch-be-service
            port:
              number: 80